# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace clkfsm.sv --exe clkfsm_tb.cpp
# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vclkfsm.mk Vclkfsm
# run executable simulation file
obj_dir/Vclkfsm